version: "3.9"
services:
  video_uploader:
    build: .
    container_name: video_uploader
    volumes:
      - ./video_mapping.json:/app/video_mapping.json
      - ./videos:/app/videos # Adjust this if using a different video directory
    environment:
      - STORAGE_MODE=${STORAGE_MODE:-local}
      - CLEAN_LOCAL=${CLEAN_LOCAL:-false}
    command: ["-json", "/app/video_mapping.json", "-storage", "${STORAGE_MODE}", "-progress"]